import assert from "node:assert/strict";
import test from "node:test";
import { authorityLabel, canFinalizeDecision, createDelegation, delegationStatus, revokeDelegation, sanitizeActorRecords, shouldResetPrototypeHistory } from "../app/authorityRules.mjs";

const draft = { id: "d1", delegateName: "Delivery lead", startsAt: "2026-07-22T10:00:00.000Z", expiresAt: "2026-07-23T10:00:00.000Z", grantedBy: "Product Owner", grantedAt: "2026-07-22T09:00:00.000Z" };

test("delegation is explicitly time bounded and immutable", () => { const delegation = createDelegation(draft); assert.equal(Object.isFrozen(delegation), true); assert.equal(delegationStatus(delegation, "2026-07-22T09:30:00.000Z"), "scheduled"); assert.equal(delegationStatus(delegation, "2026-07-22T12:00:00.000Z"), "active"); assert.equal(delegationStatus(delegation, "2026-07-23T10:00:00.000Z"), "expired"); });
test("only authenticated Product Owners or active delegates can finalize", () => { const delegation = createDelegation(draft); assert.equal(canFinalizeDecision({ authenticated: true, role: "product-owner", now: draft.startsAt }), true); assert.equal(canFinalizeDecision({ authenticated: true, role: "authorized-delegate", delegation, now: "2026-07-22T12:00:00.000Z" }), true); assert.equal(canFinalizeDecision({ authenticated: false, role: "product-owner", now: draft.startsAt }), false); assert.equal(canFinalizeDecision({ authenticated: true, role: "participant", now: draft.startsAt }), false); assert.equal(canFinalizeDecision({ authenticated: true, role: "authorized-delegate", delegation, now: draft.expiresAt }), false); });
test("revocation takes effect without altering the original grant", () => { const original = createDelegation(draft); const revoked = revokeDelegation(original, "2026-07-22T12:30:00.000Z"); assert.equal(original.revokedAt, null); assert.equal(delegationStatus(revoked, "2026-07-22T13:00:00.000Z"), "revoked"); assert.equal(canFinalizeDecision({ authenticated: true, role: "authorized-delegate", delegation: revoked, now: "2026-07-22T13:00:00.000Z" }), false); });
test("invalid and overlong grants are rejected", () => { assert.throws(() => createDelegation({ ...draft, expiresAt: draft.startsAt }), /after its start/); assert.throws(() => createDelegation({ ...draft, expiresAt: "2026-08-22T10:00:00.000Z" }), /cannot exceed/); });
test("visible authority labels never require a personal display name", () => { assert.equal(authorityLabel("product-owner"), "Product Owner"); assert.equal(authorityLabel("authorized-delegate"), "Authorized Delegate"); assert.equal(authorityLabel("participant"), "Participant"); assert.equal(authorityLabel("product-owner", false), "Unauthenticated user"); });
test("previous browser records are sanitized to role-based actors", () => { const source = [{ id: "event-1", actor: "private value" }]; const sanitized = sanitizeActorRecords(source, "Product Owner"); assert.equal(sanitized[0].actor, "Product Owner"); assert.equal(source[0].actor, "private value"); assert.equal(Object.isFrozen(sanitized[0]), true); });
test("privacy storage migration clears history exactly once", () => { assert.equal(shouldResetPrototypeHistory(undefined, 2), true); assert.equal(shouldResetPrototypeHistory(1, 2), true); assert.equal(shouldResetPrototypeHistory(2, 2), false); assert.equal(shouldResetPrototypeHistory(3, 2), false); });
